### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by jp1337** [JamesSullivan/manmosu#2]
Hi there!
Thank you for developing a clone of mamute since the project is abandoned.
Maybe you can tell me how far you have developed the clone?
Another question is if I can migrate from mamute to manmosu?
Thank you for the time and effort you spent here 👍

**Comment by JamesSullivan** [comment]
I finished the Question & Answer part but not the News part of Manmosu. Please take a look at http://manmosu.solutions.asia/ to see how far the clone went. Yes, you should be able to migrate from Mamute to Manamosu if the news part is not needed. The database tables are exactly the same. You may need to tweak a few things depending on the version of MySQL you are using. If you run into issues let me know and I will help if I can.
